# Generated by Django 4.2 on 2023-12-08 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0002_airport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airport',
            name='address',
            field=models.TextField(max_length=1000),
        ),
    ]
