# Generated by Django 4.2 on 2023-12-14 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0004_flights_origin'),
    ]

    operations = [
        migrations.AddField(
            model_name='flights',
            name='destination',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Des', to='flights.airport'),
            preserve_default=False,
        ),
    ]
