# Generated by Django 4.2 on 2023-12-15 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0005_flights_destination'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flights',
            options={'verbose_name': 'flight'},
        ),
    ]
