# Generated by Django 4.2 on 2023-12-15 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0002_alter_train_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='city',
            field=models.CharField(choices=[('TEH', 'Tehran'), ('SRI', 'Sari'), ('ISF', 'Isfahan')], max_length=20),
        ),
    ]
